services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
    - ./filestore:/config
  backend:
    build:
      context: ./backend
    volumes:
    - ./filestore:/config
